apps/common/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin

from mongoadmin.sites import site


admin.autodiscover()

js_info_dict = {
    'packages': ('common',),
}

urlpatterns = patterns(
    '',
    url(r'^accounts/', include('common.backends.registration.urls')),
    url(r'^(?P<lab_pk>[\d\w]+)/history/', include('history.urls', namespace='history')),
    url(r'^', include('labs.urls', namespace='labs')),
    url(r'^(?P<lab_pk>[\d\w]+)/experiments/', include('experiments.urls', namespace='experiments')),
    url(r'^(?P<lab_pk>[\d\w]+)/collections/', include('unit_collections.urls', namespace='collections')),
    url(r'^(?P<lab_pk>[\d\w]+)/units/', include('units.urls', namespace='units')),
    url(r'^(?P<lab_pk>[\d\w]+)/dashboard/', include('dashboard.urls', namespace='dashboard')),
    url(r'^(?P<lab_pk>[\d\w]+)/comment/', include('comments.urls', namespace='comment')),
    url(r'^(?P<lab_pk>[\d\w]+)/tags/', include('tags.urls', namespace='tags')),
    url(r'^(?P<lab_pk>[\d\w]+)/measurements/', include('measurements.urls', namespace='measurements')),
    url(r'^(?P<lab_pk>[\d\w]+)/search/', include('search.urls', namespace='search')),
    url(r'^profiles/', include('profiles.urls', namespace='profiles')),
    url(r"^(?P<lab_pk>[\d\w]+)/filemanager/", include("filemanager.urls")),
    url(r'^ckeditor/', include('ckeditor.urls')),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^admin/rosetta/', include('rosetta.urls')),
    url(r'^admin/', include(site.urls)),
    url(r'^jsi18n/$', 'django.views.i18n.javascript_catalog', js_info_dict, name='js_catalog'),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/dashboard/urls.py
from django.conf.urls import patterns, url

from .views import (DashboardView, RecentActivityView, MeasurementRecentActivityView,
                    CommentRecentActivityView)


urlpatterns = patterns(
    '',
    url(r'^$', DashboardView.as_view(), name='dashboard'),
    url(r'^experiment/all/activity/(?P<experiment_pk>[\d\w]+)/$',
        RecentActivityView.as_view(),
        name='experiment-all-activity'),
    url(r'^experiment/measurement/activity/(?P<experiment_pk>[\d\w]+)/$',
        MeasurementRecentActivityView.as_view(),
        name='experiment-measurement-activity'),
    url(r'^experiment/comment/activity/(?P<experiment_pk>[\d\w]+)/$',
        CommentRecentActivityView.as_view(),
        name='experiment-comment-activity'),

    url(r'^all/activity/$',
        RecentActivityView.as_view(),
        name='all-activity'),
    url(r'^measurement/activity/$',
        MeasurementRecentActivityView.as_view(),
        name='measurement-activity'),
    url(r'^comment/activity/$',
        CommentRecentActivityView.as_view(),
        name='comment-activity'),
)

apps/labs/urls.py
from django.conf.urls import patterns, url
from labs.views import LabCreateView, LabListView, LabUpdateView, LabDetailView, LabDeleteView, BaseLabCreateView


urlpatterns = patterns('',
    url(r'^create/lab/$', LabCreateView.as_view(), name='create'),
    url(r'^(?P<lab_pk>[\d\w]+)/detail/lab/$', LabDetailView.as_view(), name='detail'),
    url(r'^(?P<lab_pk>[\d\w]+)/update/lab/$', LabUpdateView.as_view(), name='update'),
    url(r'^(?P<lab_pk>[\d\w]+)/delete/lab/$', LabDeleteView.as_view(), name='delete'),
    url(r'^create/test/lab/$', BaseLabCreateView.as_view(), name='create_test_lab'),
    url(r'^$', LabListView.as_view(), name='list'),
)

apps/profiles/urls.py
from django.conf.urls import patterns, url
from profiles.views import InviteTechnician, ProfileFormView, ProfileDetailView


urlpatterns = patterns('',
    url(r'^$', InviteTechnician.as_view(), name='invite'),
    url(r'^update/(?P<pk>[\d\w]+)/$', ProfileFormView.as_view(), name='update'),
    url(r'^detail/(?P<pk>[\d\w]+)/$', ProfileDetailView.as_view(), name='detail'),
)

apps/labs/models.py
from documents import *

apps/labs/forms.py
# -*- coding: utf-8 -*-
from django.utils.translation import ugettext_lazy as _

from common.forms import BaseForm
from labs.documents import Lab


class LabBaseForm(BaseForm):

    def clean(self):
        data = super(LabBaseForm, self).clean()
        if 'investigator' in data:
            if 'members' in data and set(data['investigator']) & set(data['members']):
                self._errors["members"] = self.error_class(['field value \'investigator\' should not interfere with the field values \'members\''])
                del data['members']
            if 'guests' in data and set(data['investigator']) & set(data['guests']):
                self._errors["guests"] = self.error_class(['field value \'investigator\' should not interfere with the field values \'guests\''])
                del data['guests']
        return data


class LabForm(LabBaseForm):
    """
    Form for create/edit laboratory
    """
    class Meta:
        document = Lab
        fields = ('name', 'investigator', 'members', 'guests')

    def __init__(self, *args, **kwargs):
        super(LabForm, self).__init__(*args, **kwargs)
        self.fields['investigator'].widget.attrs['data-dependent'] = 'members,guests'
        self.fields['members'].widget.attrs['data-dependent'] = 'investigator,guests'
        self.fields['guests'].widget.attrs['data-dependent'] = 'members,investigator'
        self.user = self.initial['user']
        del self.initial['user']

    def clean(self):
        data = super(LabForm, self).clean()
        if self.instance and self.instance.is_member(self.user):
            if 'investigator' in self.changed_data and self.instance.investigator != data['investigator']:
                self._errors['investigator'] = self.error_class([_('You have not permission change lab\'s investigator')])
                del data['investigator']
        return data


class LabAdminForm(LabBaseForm):

    class Meta:
        document = Lab

    def clean(self):
        data = super(LabAdminForm, self).clean()
        is_test = data.get('is_test')
        labs = self._meta.document.objects.filter(is_test=True)
        if labs and is_test and (labs.count() > 1 or (self.instance and labs[0].pk != self.instance.pk)):
            self._errors['is_test'] = self.error_class(['There was only one test lab'])
        return data

apps/labs/views.py
# -*- coding: utf-8 -*-
import os

from django.contrib import messages
from django.core.urlresolvers import reverse_lazy, reverse
from django.conf import settings
from django.http import HttpResponseRedirect
from django.views.generic import CreateView, DetailView, ListView, UpdateView, DeleteView, RedirectView
from django.utils.translation import ugettext_lazy as _

from mongoengine import Q

from common.mixins import (ActiveTabMixin, LoginRequiredMixin, CheckEditPermissionMixin, CheckViewPermissionMixin,
                           CheckDeletePermissionMixin, InviteFormMixin)
from filemanager.views import check_directory
from labs.documents import Lab
from labs.forms import LabForm
from fabfile import create_test_lab

class LabCreateView(LoginRequiredMixin, InviteFormMixin, ActiveTabMixin, CreateView):
    """
     View for creating a new laboratory
    """
    model = Lab
    form_class = LabForm
    template_name = 'labs/lab_form.html'
    active_tab = 'labs'

    def form_valid(self, form):
        """
        If form is valid save create a new laboratory, if created user not in owners, add him there

        :param form: :class:`labs.forms.LabForm` instance
        :return: redirect to laboratories list
        """
        self.object = form.save(commit=False)
        if not self.request.user in self.object.investigator:
            self.object.investigator.append(self.request.user)
        self.object.save()
        check_directory(os.path.join(settings.FILEMANAGER_UPLOAD_ROOT, unicode(self.object.id) + '/'))
        self.get_success_message()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('labs:list')

    def get_success_message(self):
        return messages.add_message(self.request, messages.SUCCESS, _('Lab was added successfully.'))

    def get_initial(self):
        return {'user': self.request.user}


class LabUpdateView(LoginRequiredMixin, InviteFormMixin, CheckEditPermissionMixin, ActiveTabMixin, UpdateView):
    """
     View for updating an existing laboratory
    """
    model = Lab
    form_class = LabForm
    template_name = 'labs/lab_form.html'
    active_tab = 'labs'
    pk_url_kwarg = 'lab_pk'

    def form_valid(self, form):
        """
        If form is valid save create a new laboratory, if created user not in owners, add him there

        :param form: :class:`labs.forms.LabForm` instance
        :return: redirect to laboratories list
        """
        response = super(LabUpdateView, self).form_valid(form)
        self.get_success_message()
        return response

    def get_success_message(self):
        return messages.add_message(self.request, messages.SUCCESS, _('Lab was updated successfully.'))

    def get_initial(self):
        return {'user': self.request.user}


class LabDeleteView(LoginRequiredMixin, CheckDeletePermissionMixin, ActiveTabMixin, DeleteView):
    """
     View for removing an existing laboratory
    """
    model = Lab
    success_url = reverse_lazy('labs:list')
    active_tab = 'labs'
    pk_url_kwarg = 'lab_pk'

    def delete(self, request, *args, **kwargs):
        response = super(LabDeleteView, self).delete(request, *args, **kwargs)
        self.get_success_message()
        return response

    def get_success_message(self):
        return messages.add_message(self.request, messages.SUCCESS, _('Lab was removed successfully.'))


class LabDetailView(LoginRequiredMixin, CheckViewPermissionMixin, ActiveTabMixin, DetailView):
    """
     View for display information about an existing laboratory with related experiments
    """
    model = Lab
    template_name = 'labs/lab_detail.html'
    active_tab = 'labs'
    pk_url_kwarg = 'lab_pk'


class LabListView(LoginRequiredMixin, ActiveTabMixin, ListView):
    """
     View for display laboratories list
    """
    model = Lab
    template_name = 'labs/lab_list.html'
    active_tab = 'labs'
    pk_url_kwarg = 'lab_pk'

    def get_context_data(self, **kwargs):
        ctx = super(LabListView, self).get_context_data(**kwargs)
        queryset = super(LabListView, self).get_queryset()
        ctx['active_tab'] = self.active_tab
        return ctx

    def get_queryset(self):
        """
        Display laboratories where user is assistant
        """
        queryset = super(LabListView, self).get_queryset()
        user = self.request.user
        queryset = queryset.filter(Q(members=user) | Q(guests=user) | Q(investigator=user))
        return queryset


class BaseLabCreateView(LoginRequiredMixin, RedirectView):
    model = Lab
    url = reverse_lazy('labs:list')

    def get(self, request, *args, **kwargs):
        self.request.user.create_test_lab()
        return super(BaseLabCreateView, self).get(request, *args, **kwargs)

templates/labs/lab_detail.html
{% extends 'base.html' %}
{% load i18n %}

{% block content_header %}{% trans object.name|title %}
  <small>{% trans 'Details' %}</small>{% endblock %}

{% block manage_buttons %}
  {% if user in object.investigator %}
    <div class="btn-group pull-right">
      <button class="btn btn-danger btn-flat" data-href="{% url 'labs:delete' lab_pk=object.pk %}"
              data-toggle="modal" data-target="#confirm-delete">
        <i class="fa fa-trash"></i> {% trans 'delete'|title %}
      </button>
    </div>
    <div class="btn-group">
      <a href="{% url 'labs:update' lab_pk=object.pk %}" class="btn btn-info btn-flat">
        <i class="fa fa-edit"></i> {% trans 'edit'|title %}
      </a>
    </div>
  {% endif %}
  {% if user in object.investigator or user in object.members %}
    <div class="btn-group">
      <a href="{% url 'experiments:create' lab_pk=object.pk %}" class="btn bg-olive btn-flat">
        <i class="fa fa-plus"></i> {% trans 'Create Experiment'|title %}
      </a>
    </div>
  {% endif %}
  {% if experiments_list %}
    <div class="btn-group">
      <a href="{% url 'units:list' lab_pk=object.pk %}" class="btn bg-yellow btn-flat">
        <i class="fa fa-list"></i> {% trans 'units list'|title %}
      </a>
    </div>
  {% endif %}
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-lg-3 col-xs-6">
      {% include 'small-box_collapse.html' with obj_list=object.investigator title_box='investigators' color='yellow' icon='users' %}
    </div>
    <div class="col-lg-3 col-xs-6">
      {% include 'small-box_collapse.html' with obj_list=object.guests title_box='guests' color='red' icon='users' %}
    </div>
    <div class="col-lg-3 col-xs-6">
      {% include 'small-box_collapse.html' with obj_list=object.memebers title_box='members' color='aqua' icon='users' %}
    </div>
    <div class="col-lg-3 col-xs-6">
      {% include 'small-box_collapse.html' with obj_list=experiments_list title_box='experiments' color='olive' icon='flask' %}
    </div>
  </div>
  <!-- Left content section -->
<div class="row">
  <section class="col-lg-6">

    <div class="box box-primary">
      <div class="box-header">
        <h3 class="box-title">{% trans object.name|title %}</h3>
      </div>
      <div class="box-body">
        <dl class="dl-horizontal">
          <dt> {% trans 'Investigators' %}:</dt>
          <dd>
            {% for person in object.investigator %}
              <a href="{{ person.get_absolute_url }}">
                <i class="fa fa-user"></i>
                {{ person.full_name }}
              </a>
              {% if not forloop.last %}, {% endif %}
            {% empty %}
              {% trans 'Not a single person' %}
            {% endfor %}
          </dd>
          <dt> {% trans 'Members' %}:</dt>
          <dd>
            {% for person in object.members %}
              <a href="{{ person.get_absolute_url }}">
                <i class="fa fa-user"></i>
                {{ person.full_name }}
              </a>
              {% if not forloop.last %}, {% endif %}
            {% empty %}
              {% trans 'Not a single person' %}
            {% endfor %}
          </dd>
          <dt> {% trans 'Guests' %}:</dt>
          <dd>
            {% for person in object.guests %}
              <a href="{{ person.get_absolute_url }}">
                <i class="fa fa-user"></i>
                {{ person.full_name }}
              </a>
              {% if not forloop.last %}, {% endif %}
            {% empty %}
              {% trans 'Not a single person' %}
            {% endfor %}
          </dd>
        </dl>
      </div>
      <!--<div class="list-group col-lg-11">
        <div class="col-sm-4 title-desc">{% trans 'name'|title %}</div>
        <div class="col-sm-8">
          <ul class="list-group">
            <li class="list-group-item list-group-item-sm">{{ object.name }}</li>
          </ul>
        </div>
        <div class="col-sm-4 title-desc">{% trans 'investigators'|title %}</div>
        <div class="col-sm-8">
          <ul class="list-group">
            {% for member in object.investigator %}
              <li class="list-group-item list-group-item-sm">
                <a href="{{ member.get_absolute_url }}">{{ member.full_name }}</a></li>
            {% endfor %}
            {% if not object.investigator %}
              <li class="list-group-item list-group-item-sm">&nbsp;</li>
            {% endif %}
          </ul>
        </div>
        <div class="col-sm-4 title-desc">{% trans 'members'|title %}</div>
        <div class="col-sm-8">
          <ul class="list-group">
            {% for member in object.members %}
              <li class="list-group-item list-group-item-sm"><a
                  href="{{ member.get_absolute_url }}">{{ member.full_name }}</a></li>
            {% endfor %}
            {% if not object.members %}
              <li class="list-group-item list-group-item-sm">&nbsp;</li>
            {% endif %}
          </ul>
        </div>
        <div class="col-sm-4 title-desc">{% trans 'guests'|title %}</div>
        <div class="col-sm-8">
          <ul class="list-group">
            {% for member in object.guests %}
              <li class="list-group-item list-group-item-sm"><a
                  href="{{ member.get_absolute_url }}">{{ member.full_name }}</a></li>
            {% endfor %}
            {% if not object.guests %}
              <li class="list-group-item list-group-item-sm">&nbsp;</li>
            {% endif %}
          </ul>
        </div>
      </div>-->
    </div>
  </section>
  <!-- end left content section -->

  <!-- Right content section -->
  <section class="col-lg-6">
    {% if experiments_list %}
        <div class="box">
          <div class="box-header"><h3 class="box-title">{% trans 'experiments'|title %}</h3></div>
          <div class="box-body">
            <div class="list-group">
              {% for experiment in experiments_list %}
                <a href="{{ experiment.get_absolute_url }}" class="list-group-item list-group-item-sm">
                  {{ experiment }}
                </a>
              {% endfor %}
            </div>
          </div>
        </div>
    {% endif %}
  </section>
  </div>
  <!-- end right content section -->
{% endblock %}
{% block modal %}{% include 'alert.html' with obj=object.name %}{% endblock %}

templates/labs/lab_form.html
{% extends 'base.html' %}

{% load i18n bootstrap_tags %}

{% block modal %}
  {% url 'profiles:invite' as action %}
  {% include 'modal.html' with fields='investigator,members,guests' class='invite-member' button_name='invite'|upper modal_title='invite members' %}
{% endblock %}

{% block manage_buttons %}
  <div class="text-right">
    <div class="btn-group">
      <a href="#" data-toggle="modal" data-target="#modal" class="btn bg-aqua btn-sm btn-flat">
        <i class="ion ion-person-add"></i> {% trans 'invite members'|upper %}
      </a>
    </div>
  </div>
{% endblock %}

{% block content %}
  <div class="col-md-offset-2 col-md-8 col-sm-12">
    <div class="box box-solid">
      <form method="post">
        <div class="box-body">
          {% csrf_token %}
          {{ form|as_bootstrap }}
        </div>

        <div class="box-footer form-actions text-right">
          <button type="submit" class="btn bg-olive btn-sm btn-flat btn-block">
            <i class="fa fa-save"></i> {% trans 'Save'|upper %}
          </button>
        </div>
      </form>
    </div>
  </div>
{% endblock %}

{% block form_script %}{{ form.media }}{% endblock %}

templates/labs/lab_list.html
{% extends 'base.html' %}

{% load i18n %}
{% block content_header %}{% trans 'Home' %}{% endblock %}
{% block content %}
  <div class="col-md-offset-2 col-md-8 col-sm-12">

    {% if not object_list %}
      <div class="box box-solid">
        <div class="box-footer">
          <a class="btn btn-primary btn-block btn-flat" href="{% url 'labs:create_test_lab' %}">
            <i class="fa fa-plus"></i> <i class="fa fa-plus"></i> {% trans 'Create <i>test</i> lab' %}
          </a>
          <a href="{% url 'labs:create' %}" class="btn btn-default btn-block btn-flat">
            <i class="fa fa-plus"></i> {% trans 'Create empty lab' %}
          </a>
        </div>
      </div>
    {% else %}
      <div class="box box-solid box-info">
        <div class="box-header">
          <i class="fa fa-flask"></i>

          <h3 class="box-title"> {% trans 'Laboratories' %}</h3>
        </div>
        <div class="box-body">
          <div class="box-group" id="accordion">
            <!-- we are adding the .panel class so bootstrap.js collapse plugin detects it -->
            {% for object in object_list %}
              <div class="panel box">
                <div class="box-header">
                  <h4 class="box-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#{{ object.name|slugify }}"
                       class="collapsed">
                      {{ object.name|title }}
                    </a>
                  </h4>

                  <div class="box-tools pull-right">
                    <a href="{% url 'dashboard:dashboard' lab_pk=object.pk %}"
                       class="btn btn-flat btn-sm " title="{% trans 'Go to the lab' %}">
                      <i class="fa fa-arrow-right"></i>
                    </a>
                  </div>
                </div>
                <div id="{{ object.name|slugify }}" class="panel-collapse collapse" style="height: 0px;">
                  <div class="box-body">
                    <dl class="dl-horizontal">
                      <dt><i class="fa fa-users"></i> {% trans 'Investigators' %}:</dt>
                      <dd>
                        {% for person in object.investigator %}
                          <a href="{{ person.get_absolute_url }}">
                            <i class="fa fa-user"></i>
                            {{ person.full_name }}
                          </a>
                          {% if not forloop.last %}, {% endif %}
                        {% empty %}
                          {% trans 'Not a single person' %}
                        {% endfor %}
                      </dd>
                      <dt><i class="fa fa-users"></i> {% trans 'Members' %}:</dt>
                      <dd>
                        {% for person in object.members %}
                          <a href="{{ person.get_absolute_url }}">
                            <i class="fa fa-user"></i>
                            {{ person.full_name }}
                          </a>
                          {% if not forloop.last %}, {% endif %}
                        {% empty %}
                          {% trans 'Not a single person' %}
                        {% endfor %}
                      </dd>
                      <dt><i class="fa fa-users"></i> {% trans 'Guests' %}:</dt>
                      <dd>
                        {% for person in object.guests %}
                          <a href="{{ person.get_absolute_url }}">
                            <i class="fa fa-user"></i>
                            {{ person.full_name }}
                          </a>
                          {% if not forloop.last %}, {% endif %}
                        {% empty %}
                          {% trans 'Not a single person' %}
                        {% endfor %}
                      </dd>
                    </dl>
                  </div>
                </div>
              </div>
            {% endfor %}
          </div>
        </div>
        <div class="box-footer">
          <a class="btn btn-primary btn-block btn-flat" href="{% url 'labs:create_test_lab' %}">
            <i class="fa fa-plus"></i> {% trans 'Create <i>demo</i> lab' %}
          </a>
          <a href="{% url 'labs:create' %}" class="btn btn-default btn-block btn-flat">
            <i class="fa fa-plus"></i> {% trans 'Create empty lab' %}
          </a>
        </div>
      </div>
    {% endif %}
  </div>
{% endblock %}