apps/common/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin

from mongoadmin.sites import site


admin.autodiscover()

js_info_dict = {
    'packages': ('common',),
}

urlpatterns = patterns(
    '',
    url(r'^accounts/', include('common.backends.registration.urls')),
    url(r'^(?P<lab_pk>[\d\w]+)/history/', include('history.urls', namespace='history')),
    url(r'^', include('labs.urls', namespace='labs')),
    url(r'^(?P<lab_pk>[\d\w]+)/experiments/', include('experiments.urls', namespace='experiments')),
    url(r'^(?P<lab_pk>[\d\w]+)/collections/', include('unit_collections.urls', namespace='collections')),
    url(r'^(?P<lab_pk>[\d\w]+)/units/', include('units.urls', namespace='units')),
    url(r'^(?P<lab_pk>[\d\w]+)/dashboard/', include('dashboard.urls', namespace='dashboard')),
    url(r'^(?P<lab_pk>[\d\w]+)/comment/', include('comments.urls', namespace='comment')),
    url(r'^(?P<lab_pk>[\d\w]+)/tags/', include('tags.urls', namespace='tags')),
    url(r'^(?P<lab_pk>[\d\w]+)/measurements/', include('measurements.urls', namespace='measurements')),
    url(r'^(?P<lab_pk>[\d\w]+)/search/', include('search.urls', namespace='search')),
    url(r'^profiles/', include('profiles.urls', namespace='profiles')),
    url(r"^(?P<lab_pk>[\d\w]+)/filemanager/", include("filemanager.urls")),
    url(r'^ckeditor/', include('ckeditor.urls')),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^admin/rosetta/', include('rosetta.urls')),
    url(r'^admin/', include(site.urls)),
    url(r'^jsi18n/$', 'django.views.i18n.javascript_catalog', js_info_dict, name='js_catalog'),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/experiments/urls.py
from django.conf.urls import patterns, url
from experiments.views import (ExperimentCreateView, ExperimentDetailView, ExperimentUpdateView, ExperimentUpdateDateView,
                               ExperimentDeleteView, ExperimentAddUnits)


urlpatterns = patterns('',
    url(r'^create/$', ExperimentCreateView.as_view(), name='create'),
    url(r'^update/(?P<pk>[\d\w]+)/$', ExperimentUpdateView.as_view(), name='update'),
    url(r'^edit/(?P<pk>[\d\w]+)/$', ExperimentUpdateDateView.as_view(), name='update-date'),
    url(r'^delete/(?P<pk>[\d\w]+)/$', ExperimentDeleteView.as_view(), name='delete'),
    url(r'^detail/(?P<pk>[\d\w]+)/$', ExperimentDetailView.as_view(), name='detail'),

    url(r'^add_units/$', ExperimentAddUnits.as_view(), name='add-units'),
)

apps/labs/urls.py
from django.conf.urls import patterns, url
from labs.views import LabCreateView, LabListView, LabUpdateView, LabDetailView, LabDeleteView, BaseLabCreateView


urlpatterns = patterns('',
    url(r'^create/lab/$', LabCreateView.as_view(), name='create'),
    url(r'^(?P<lab_pk>[\d\w]+)/detail/lab/$', LabDetailView.as_view(), name='detail'),
    url(r'^(?P<lab_pk>[\d\w]+)/update/lab/$', LabUpdateView.as_view(), name='update'),
    url(r'^(?P<lab_pk>[\d\w]+)/delete/lab/$', LabDeleteView.as_view(), name='delete'),
    url(r'^create/test/lab/$', BaseLabCreateView.as_view(), name='create_test_lab'),
    url(r'^$', LabListView.as_view(), name='list'),
)

apps/search/urls.py
from django.conf.urls import patterns, url
from .views import ElasticSearchView


urlpatterns = patterns('',
    url(r'^$', ElasticSearchView.as_view(), name='all'),
)

apps/experiments/models.py
from documents import *

apps/experiments/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.utils.translation import ugettext_lazy as _

from mongoengine import Q

from common.forms import BaseForm, SelectFormMixin, CheckOwnerEditMixin
from common.widgets import DateTimeWidget, CKEditorUploadWidget
from experiments.documents import Experiment
from units.documents import Unit


class ExperimentForm(SelectFormMixin, CheckOwnerEditMixin, BaseForm):

    class Meta:
        document = Experiment
        fields = ('title', 'owners', 'editors', 'viewers', 'start', 'end', 'description', 'status')

    def __init__(self, *args, **kwargs):
        super(ExperimentForm, self).__init__(*args, **kwargs)
        self.fields['start'] = forms.DateTimeField(label=_('start'), input_formats=('%m/%d/%Y %H:%M',),
                                                   widget=DateTimeWidget(format='%m/%d/%Y %H:%M', attrs={'class': 'form-control'}))
        self.fields['end'] = forms.DateTimeField(label=_('end'), input_formats=('%m/%d/%Y %H:%M',),
                                                 widget=DateTimeWidget(format='%m/%d/%Y %H:%M', attrs={'class': 'form-control'}))
        lab = self.initial['lab']
        self.user = self.initial['user']
        del self.initial['user']
        self.fields['description'].widget = CKEditorUploadWidget(config_name='ckeditor', lab_pk=lab.pk)

    def clean(self):
        data = super(ExperimentForm, self).clean()
        if data.get('start') and data.get('end') and data.get('start') > data.get('end'):
            self._errors['start'] = self.error_class([_('Start date must be less than end date')])
            del data['start']
        return data


class ExperimentUpdateForm(BaseForm):

    class Meta:
        document = Experiment
        fields = ('start', 'end')


class UpdateUnitsForm(BaseForm):
    """
    Used to add units to a experiment. TODO: remove model form?
    """
    experiment = forms.ModelChoiceField(queryset=Experiment.objects.none())
    units = forms.ModelMultipleChoiceField(queryset=Unit.objects.none())

    class Meta:
        document = Experiment
        fields = ('',)

    def __init__(self, *args, **kwargs):
        self.lab = kwargs['initial']['lab']
        self.user = kwargs['initial']['user']

        super(UpdateUnitsForm, self).__init__(*args, **kwargs)
        del self.initial['user']
        del self.initial['lab']
        experiment = Experiment.objects.filter(lab=self.lab.pk)
        if not self.lab.is_owner(self.user):
            experiment = experiment.filter((Q(owners__in=[self.user]) | Q(editors__in=[self.user]) |
                                              Q(viewers__in=[self.user]) | Q(units__in=self.fields['units'].queryset)))
        self.fields['experiment'].queryset = experiment

        self.fields['units'].queryset = Unit.objects.filter(lab=self.lab, active=True)

        self.fields['units'].widget.attrs['class'] += ' hidden-field'
        self.fields['units'].label = ''
        self.fields['units'].error_messages['required'] = _('You didn\'t select any units.')

apps/experiments/views.py
# -*- coding: utf-8 -*-
import dateutil
import json

from django.contrib import messages
from django.core.urlresolvers import reverse_lazy, reverse
from django.http import HttpResponseRedirect
from django.template.loader import render_to_string
from django.utils.decorators import method_decorator
from django.utils.translation import gettext_lazy as _, ugettext
from django.utils.safestring import mark_safe
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView, View
from django.views.generic.edit import ModelFormMixin, ProcessFormView

from comments.documents import Comment
from common.decorators import get_obj_or_404

from common.mixins import (ActiveTabMixin, CheckEditPermissionMixin, CheckViewPermissionMixin, JsTreeMixin,
                           LabQueryMixin, CheckDeletePermissionMixin, RecentActivityMixin, CommentMixin,
                           AjaxableResponseMixin, InviteFormMixin, CheckLabPermissionMixin,
                           FormInitialMixin, LoginRequiredMixin)
from dashboard.documents import RecentActivity
from experiments.documents import Experiment
from experiments.forms import ExperimentForm, ExperimentUpdateForm, UpdateUnitsForm
from tags.documents import Tag
from units.documents import Unit
from units.forms import UnitForm, UnitPopupForm


class ExperimentCreateView(CheckLabPermissionMixin, LabQueryMixin, FormInitialMixin, InviteFormMixin, ActiveTabMixin,
                           RecentActivityMixin, CreateView):
    """
     View for creating a new experiment
    """
    model = Experiment
    form_class = ExperimentForm
    template_name = 'experiments/experiment_form.html'
    active_tab = 'experiments'

    def form_valid(self, form):
        """
        If form is valid save create a new experiment, if created user not in owners, add him there

        :param form: :class:`experiments.forms.ExperimentForm` instance
        :return: redirect to detail laboratory's information
        """
        self.object = form.save(commit=False)
        if not self.request.user in self.object.owners:
            self.object.owners.append(self.request.user)
        self.object.lab = self.lab
        if not set(self.lab.investigator) & set(self.object.owners):
            self.object.owners.extend(list(set(self.lab.investigator) - set(self.object.owners)))
        self.object.save()
        self.save_recent_activity(RecentActivity.ADD, experiment=unicode(self.object.pk))
        self.get_success_message()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return self.lab.get_absolute_url()

    def get_success_message(self):
        return messages.add_message(self.request, messages.SUCCESS, _('Experiment was added successfully.'))


class ExperimentUpdateView(CheckLabPermissionMixin, InviteFormMixin, CheckEditPermissionMixin, LabQueryMixin,
                           RecentActivityMixin, UpdateView):
    """
    View for updating an existing experiment
    """
    model = Experiment
    form_class = ExperimentForm
    template_name = 'experiments/experiment_form.html'

    def form_valid(self, form):
        """
        If form is valid save update an experiment, if updated user not in owners, add him there

        :param form: :class:`experiments.forms.ExperimentForm` instance
        :return: redirect to detail laboratory's information
        """
        lab = self.object.lab
        self.object = form.save(commit=False)
        if not set(lab.investigator) & set(self.object.owners):
            self.object.owners.extend(list(set(lab.investigator) - set(self.object.owners)))
        self.object.lab = lab
        self.object.save()
        self.save_recent_activity(RecentActivity.UPDATE, experiment=unicode(self.object.pk))
        self.get_success_message()
        return HttpResponseRedirect(self.get_success_url())

    @method_decorator(get_obj_or_404)
    def get_initial(self):
        self.initial = {'lab': self.object.lab, 'user': self.request.user}
        return super(ExperimentUpdateView, self).get_initial()

    def get_success_url(self):
        return reverse('experiments:detail', kwargs={'pk': self.object.pk, 'lab_pk': self.object.lab.pk})

    def get_success_message(self):
        return messages.add_message(self.request, messages.SUCCESS, _('Experiment was updated successfully.'))


class ExperimentUpdateDateView(CheckLabPermissionMixin, CheckEditPermissionMixin, LabQueryMixin,
                               RecentActivityMixin, AjaxableResponseMixin, UpdateView):
    """
    View for updating date an existing experiment
    """
    model = Experiment
    form_class = ExperimentUpdateForm
    template_name = 'dashboard/resent.html'

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        data = self.request.POST
        self.object.start = dateutil.parser.parse(data['start'])
        self.object.end = dateutil.parser.parse(data['end'])
        self.object.save()
        resent = self.save_recent_activity(RecentActivity.UPDATE, experiment=unicode(self.object.pk))
        return self.render_to_json_response({'data': render_to_string(self.template_name, {'object': resent})})


class ExperimentDeleteView(CheckLabPermissionMixin, CheckDeletePermissionMixin, LabQueryMixin, ActiveTabMixin,
                           RecentActivityMixin, DeleteView):
    """
    View for removing an existing experiment
    """
    model = Experiment
    active_tab = 'experiments'

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.active = False
        self.object.save()
        self.save_recent_activity(RecentActivity.DELETE, **{self.model._meta.object_name.lower(): self.object.pk})
        self.get_success_message()
        return HttpResponseRedirect(success_url)

    def get_success_url(self):
        return reverse_lazy('labs:detail', kwargs={'lab_pk': self.kwargs.get('lab_pk')})

    def get_success_message(self):
        return messages.add_message(self.request, messages.SUCCESS, _('Experiment was removed successfully.'))


class ExperimentDetailView(CheckLabPermissionMixin, JsTreeMixin, CheckViewPermissionMixin, LabQueryMixin, CommentMixin, DetailView):
    """
    View for display information about an existing experiment with related units
    """
    model = Experiment
    template_name = 'experiments/experiment_detail.html'
    paginate_by = 5
    form = UnitPopupForm

    def get_unit_graph_data(self):
        """
        Return json data for units graph
        """
        units = list(self.units)
        graph_data = dict()

        graph_data['graph'] = []
        graph_data['directed'] = False
        graph_data['multigraph'] = False

        nodes = []
        links = []

        for index, unit in enumerate(units):
            node = {
                "size": 1,
                "score": 2,
                "id": u'{}'.format(unit.pk),
                "text": u'{}'.format(unit.sample),
                "type": "circle",
                'link': unit.get_absolute_url(),
            }
            nodes.append(node)
            if not unit.parent:
                continue
            for parent in unit.parent:
                if parent in units:
                    link = {
                        'target': index,
                        'source': units.index(parent),
                        'arrow': True
                    }
                    links.append(link)

        graph_data['nodes'] = nodes
        graph_data['links'] = links

        return mark_safe(json.dumps(graph_data))

    def get_context_data(self, **kwargs):
        ctx = super(ExperimentDetailView, self).get_context_data(**kwargs)
        ctx['units'] = self.units

        tags = Tag.objects.filter(lab=self.kwargs.get('lab_pk'))
        tags_tree = self.get_jstree_data(tags, ('id', 'parent', 'details'), parent_id='#')
        ctx['tags'] = json.dumps(tags_tree)

        ctx['units_graph_json'] = self.get_unit_graph_data()

        ctx['unit_form'] = UnitPopupForm(lab_pk=self.lab.pk, exp_pk=self.object.pk)
        return ctx

    def get_list_comment(self):
        self.units = Unit.objects.filter(experiments=self.object, active=True)
        queryset = list(super(ExperimentDetailView, self).get_list_comment())
        queryset += list(Comment.objects.filter(instance_type='Unit', object_id__in=self.units.values_list('pk')))
        return queryset


class ExperimentAddUnits(LoginRequiredMixin, CheckLabPermissionMixin, FormInitialMixin, AjaxableResponseMixin,
                          RecentActivityMixin, ModelFormMixin, ProcessFormView, View):
    """
    Add units to experimetn
    """
    model = Experiment
    form_class = UpdateUnitsForm

    def post(self, request, *args, **kwargs):
        self.object = None
        return super(ExperimentAddUnits, self).post(request, *args, **kwargs)

    def form_valid(self, form):

        self.object = form.cleaned_data['experiment']
        for unit in form.cleaned_data['units']:
            unit.update(
                add_to_set__experiments=self.object)
            unit.save(user=self.request.user)

        self.save_recent_activity(RecentActivity.UPDATE)
        self.get_success_message()
        return self.render_to_json_response({'message': self.get_success_message()})

    def get_success_message(self):
        return ugettext(u'Experiment was changed successfully.')

templates/search/collection_form.html
{% load i18n %}

<span class="non-field-error has-error pull-left" role="alert">
    {{ form.non_field_errors.0 }}
</span>

{% for field in update_collection_form.visible_fields %}
  <div class="form-group col-sm-8">
    <div class="input-group col-sm-12{% if field.errors %} has-error{% endif %}">
      {% include 'field.html' with field_width=-3 label_width=3 %}
    </div>
  </div>
{% endfor %}
{% for field in update_collection_form.hidden_fields %}
  {{ field }}
{% endfor %}
<button class="btn btn-sm btn-info">{% trans 'add to existing collection'|title %}</button>
{{ update_collection_form.media }}

templates/search/experiment_form.html
{% load i18n %}

<span class="non-field-error has-error pull-left" role="alert">
    {{ form.non_field_errors.0 }}
</span>

{% for field in update_experiment_form.visible_fields %}
  <div class="form-group col-sm-8">
    <div class="input-group col-sm-12{% if field.errors %} has-error{% endif %}">
      {% include 'field.html' with field_width=-5 label_width=5 %}
    </div>
  </div>
{% endfor %}
{% for field in update_experiment_form.hidden_fields %}
  {{ field }}
{% endfor %}
<button class="btn btn-sm btn-info">{% trans 'add to experiment'|title %}</button>
{{ update_experiment_form.media }}

templates/search/search_list.html
{% extends 'base.html' %}

{% load static i18n  bootstrap_tags %}

{% block content %}

  <div class="col-xs-12">
    <div class="box box-solid">
      <div class="box-body">
        <form method="get">
          <div class="input-group">
            {{ form|as_bootstrap }}
            <ul class="nav nav-pills nav-justified" id="search-component"></ul>
            <span class="input-group-btn top-vertical-align">
                <button type="submit" name="search" title="Search" id="search-btn" class="btn btn-flat btn-info">
                  <i class="fa fa-search"></i>
                </button>
            </span>
          </div>
        </form>
      </div>
    </div>
  </div>
  <div class="col-sm-12">
    <div class="nav-tabs-custom">
      <ul class="nav nav-tabs">
        {% if experiments %}
          <li class="active"><a href="#experiment" data-toggle="tab">
            <i class="fa fa-eyedropper"></i> {% trans 'Experiments' %}</a></li>
        {% endif %}
        {% if units %}
          <li class=""><a href="#unit" data-toggle="tab">
            <i class="fa fa-cubes"></i> {% trans 'Units' %}</a></li>
        {% endif %}
        {% if measurements %}
          <li class=""><a href="#measurement" data-toggle="tab">{% trans 'Measurement' %}</a></li>
        {% endif %}
        {% if comments %}
          <li class=""><a href="#comment" data-toggle="tab">
            <i class="fa fa-comments-o"></i> {% trans 'Comments' %}</a></li>
        {% endif %}
        {% if profiles %}
          <li {% if not comments and not measurements and not units and not experiments %}class="active"{% endif %}><a
              href="#profile" data-toggle="tab">
            <i class="fa fa-users"></i> {% trans 'Profiles' %}</a></li>
        {% endif %}
      </ul>
      <div class="tab-content search-content">
        {% if experiments %}
          <div class="tab-pane active" id="experiment">
            <div class="panel panel-default resent-activities">
              <ul class="list-group">
                {% for result in experiments %}
                  <li class="list-group-item"><a href="{{ result.url }}">{{ result.title }}</a></li>
                {% endfor %}
              </ul>
            </div>
          </div><!-- /.tab-pane -->
        {% endif %}
        {% if units %}
          <div class="tab-pane" id="unit">
            <div class="panel panel-default resent-activities">
              <ul class="list-group">
                {% for result in units %}
                  <li class="list-group-item">
                    <label><input type="checkbox" value="{{ result.id }}" name="{{ result.sample }}"></label>
                    <a href="{{ result.url }}">{{ result.sample }}</a>
                  </li>
                {% endfor %}
              </ul>
              <div class="col-sm-12">
                {% if update_experiment_form.fields.experiment.queryset %}
                  <form class="form-inline update-experiment-form col-sm-4" role="form" method="post"
                        action="{% url 'experiments:add-units' lab_pk=lab.pk %}">{% csrf_token %}
                    {% include 'search/experiment_form.html' %}
                  </form>
                {% endif %}

               {# <button class="btn btn-sm btn-info pull-left" data-toggle="modal" #}
               {#        data-target="#modal">{% trans 'create new collection'|title %}</button>#}
               {# {% url 'collections:create' lab_pk=lab.pk as create_collection_url %}#}
               {# {% include 'modal.html' with extra_form=create_collection_form action=create_collection_url class='create-collection-form' %} #}
              </div>
            </div>
          </div><!-- /.tab-pane -->
        {% endif %}
        {% if measurements %}
          <div class="tab-pane" id="measurement">
            <div class="panel panel-default resent-activities">
              <ul class="list-group">
                {% for result in measurements %}
                  <li class="list-group-item"><a href="{{ result.url }}">{{ result.description|safe }}</a></li>
                {% endfor %}
              </ul>
            </div>
          </div><!-- /.tab-pane -->
        {% endif %}
        {% if comments %}
          <div class="tab-pane" id="comment">
            <div class="panel panel-default resent-activities">
              <ul class="list-group">
                {% for result in comments %}
                  <li class="list-group-item"><a href="{{ result.url }}">{{ result.init_user.email }}
                    : {{ result.text|safe }}</a></li>
                {% endfor %}
              </ul>
            </div>
          </div><!-- /.tab-pane -->
        {% endif %}
        {% if profiles %}
          <div
              class="tab-pane{% if not comments and not measurements and not units and not experiments %} active{% endif %}"
              id="profile">
            <div class="panel panel-default resent-activities">
              <ul class="list-group">
                {% for result in profiles %}
                  <li class="list-group-item"><a href="{{ result.url }}">{{ result.email }}</a></li>
                {% endfor %}
              </ul>
            </div>
          </div><!-- /.tab-pane -->
        {% endif %}
      </div>
      <!-- /.tab-content -->
    </div>
  </div>

{% endblock %}


{% block script %}

  <script src="{% static 'js/search.js' %}"></script>

{% endblock %}