apps/common/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin

from mongoadmin.sites import site


admin.autodiscover()

js_info_dict = {
    'packages': ('common',),
}

urlpatterns = patterns(
    '',
    url(r'^accounts/', include('common.backends.registration.urls')),
    url(r'^(?P<lab_pk>[\d\w]+)/history/', include('history.urls', namespace='history')),
    url(r'^', include('labs.urls', namespace='labs')),
    url(r'^(?P<lab_pk>[\d\w]+)/experiments/', include('experiments.urls', namespace='experiments')),
    url(r'^(?P<lab_pk>[\d\w]+)/collections/', include('unit_collections.urls', namespace='collections')),
    url(r'^(?P<lab_pk>[\d\w]+)/units/', include('units.urls', namespace='units')),
    url(r'^(?P<lab_pk>[\d\w]+)/dashboard/', include('dashboard.urls', namespace='dashboard')),
    url(r'^(?P<lab_pk>[\d\w]+)/comment/', include('comments.urls', namespace='comment')),
    url(r'^(?P<lab_pk>[\d\w]+)/tags/', include('tags.urls', namespace='tags')),
    url(r'^(?P<lab_pk>[\d\w]+)/measurements/', include('measurements.urls', namespace='measurements')),
    url(r'^(?P<lab_pk>[\d\w]+)/search/', include('search.urls', namespace='search')),
    url(r'^profiles/', include('profiles.urls', namespace='profiles')),
    url(r"^(?P<lab_pk>[\d\w]+)/filemanager/", include("filemanager.urls")),
    url(r'^ckeditor/', include('ckeditor.urls')),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^admin/rosetta/', include('rosetta.urls')),
    url(r'^admin/', include(site.urls)),
    url(r'^jsi18n/$', 'django.views.i18n.javascript_catalog', js_info_dict, name='js_catalog'),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/history/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from mongoadmin.sites import site

from history.views import HistoryListView, HistoryDetailView


admin.autodiscover()


urlpatterns = patterns('',
    url(r'^(?P<class_name>\w+)/(?P<pk>[\d\w]+)/$', HistoryListView.as_view(), name='list'),
    url(r'^(?P<pk>[\d\w]+)/$', HistoryDetailView.as_view(), name='detail'),
)

apps/labs/urls.py
from django.conf.urls import patterns, url
from labs.views import LabCreateView, LabListView, LabUpdateView, LabDetailView, LabDeleteView, BaseLabCreateView


urlpatterns = patterns('',
    url(r'^create/lab/$', LabCreateView.as_view(), name='create'),
    url(r'^(?P<lab_pk>[\d\w]+)/detail/lab/$', LabDetailView.as_view(), name='detail'),
    url(r'^(?P<lab_pk>[\d\w]+)/update/lab/$', LabUpdateView.as_view(), name='update'),
    url(r'^(?P<lab_pk>[\d\w]+)/delete/lab/$', LabDeleteView.as_view(), name='delete'),
    url(r'^create/test/lab/$', BaseLabCreateView.as_view(), name='create_test_lab'),
    url(r'^$', LabListView.as_view(), name='list'),
)

apps/history/models.py
from documents import *

apps/history/views.py
from django.views.generic import ListView, DetailView
from mongoreversion.models import ContentType

from common.mixins import LoginRequiredMixin, CheckViewPermissionMixin
from history.documents import History


class HistoryListView(LoginRequiredMixin, ListView):
    """
    View for display all history about object (unit or measurement).
    """
    model = History
    template_name = 'history/history_list.html'

    def get_queryset(self):
        try:
            instance_type = ContentType.objects.get(class_name__iexact=self.kwargs['class_name'])
            user = self.request.user
            queryset = self.model.objects.filter(instance_type=instance_type, instance_id=self.kwargs['pk']).order_by('-timestamp')
            # todo change
            exclude_pk = []
            for query in queryset:
                if not query.is_assistant(user):
                    exclude_pk.append(query.pk)
            return queryset.filter(pk__not__in=exclude_pk)
        except ContentType.DoesNotExist:
            return ContentType.objects.none()


class HistoryDetailView(LoginRequiredMixin, CheckViewPermissionMixin, DetailView):
    """
    View for display detailed information about object (unit or measurement), who and why was created or changed it.
    """
    model = History
    template_name = 'history/history_detail.html'

templates/history/history_detail.html
{% extends 'base.html' %}

{% load i18n common_tags %}

{% block breadcrumb %}
  {% with obj=object.get_object %}
    {% if obj.experiments %}
      <li>
        {% for expriment in obj.experiments %}
          <a href="{{ experiment.get_absolute_url }}">{{ expriment }}</a>&nbsp;
        {% endfor %}
      </li>
    {% endif %}
    <li><a href="{{ obj.get_absolute_url }}">{{ obj|title }}</a></li>
  {% endwith %}
  <li><a
      href="{% url 'history:list' class_name=object.instance_type.class_name pk=object.instance_id lab_pk=lab.pk %}">{% trans 'Histories' %}</a>
  </li>
  <li class="active">{{ object|title }}</li>
{% endblock %}

{% block content %}
  <ul class="list-group col-sm-7">
    <li class="list-group-item">{{ object.user.email }}</li>
    <li class="list-group-item">{{ object.timestamp }}</li>
    <li class="list-group-item">{{ object.comment }}</li>
    <li class="list-group-item">
      {% trans 'Data' %}
      <ul class="list-group">
        {% for data, value in object.instance_data.items %}
          {% if data != 'id' %}
            <li class="list-group-item">
              {{ data }} :
              {% if value.get_absolute_url %}
                <a href="{{ value.get_absolute_url }}">{{ value|default:'-' }}</a>
              {% elif value|check_list %}
                <ul>
                  {% for v in value %}
                    <li><a href="{{ v.get_absolute_url }}">{{ v|default:'-' }}</a></li>
                  {% endfor %}
                </ul>
              {% else %}
                {{ value|default:'-' }}
              {% endif %}
            </li>
          {% endif %}
        {% endfor %}
      </ul>
    </li>
  </ul>
{% endblock %}

templates/history/history_list.html
{% extends 'base.html' %}

{% load i18n %}

{% block breadcrumb %}
  {% with object=object_list.0.get_object %}
    {% if object %}
      {% if object.experiments %}
        <li>
          {% for expriment in object.experiments %}
            <a href="{{ experiment.get_absolute_url }}">{{ expriment }}</a>&nbsp;
          {% endfor %}
        </li>
      {% endif %}
      <li><a href="{{ object.get_absolute_url }}">{{ object|title }}</a></li>
    {% endif %}
  {% endwith %}
  <li class="active">{% trans 'Revision' %}</li>
{% endblock %}

{% block content %}
  <div class="col-sm-6">
    <div class="list-group col-sm-12">
      <ul class="list-group">
        {% for revision in object_list %}
          <li class="list-group-item">
            <a href="{% url 'history:detail' pk=revision.pk lab_pk=lab.pk %}">
              {{ revision.timestamp }} - {{ revision.user.email }}, {{ revision.comment }}
            </a>
          </li>
        {% endfor %}
      </ul>
    </div>
  </div>
{% endblock %}