apps/comments/urls.py
from django.conf.urls import patterns, url

from .views import CommentCreateView, CommentUpdateView, CommentDeleteView


urlpatterns = patterns('',
    url(r'^$', CommentCreateView.as_view(), name='comment'),
    url(r'^(?P<pk>[\d\w]+)/update/$', CommentUpdateView.as_view(), name='update'),
    url(r'^(?P<pk>[\d\w]+)/remove/$', CommentDeleteView.as_view(), name='delete'),
)

apps/common/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin

from mongoadmin.sites import site


admin.autodiscover()

js_info_dict = {
    'packages': ('common',),
}

urlpatterns = patterns(
    '',
    url(r'^accounts/', include('common.backends.registration.urls')),
    url(r'^(?P<lab_pk>[\d\w]+)/history/', include('history.urls', namespace='history')),
    url(r'^', include('labs.urls', namespace='labs')),
    url(r'^(?P<lab_pk>[\d\w]+)/experiments/', include('experiments.urls', namespace='experiments')),
    url(r'^(?P<lab_pk>[\d\w]+)/collections/', include('unit_collections.urls', namespace='collections')),
    url(r'^(?P<lab_pk>[\d\w]+)/units/', include('units.urls', namespace='units')),
    url(r'^(?P<lab_pk>[\d\w]+)/dashboard/', include('dashboard.urls', namespace='dashboard')),
    url(r'^(?P<lab_pk>[\d\w]+)/comment/', include('comments.urls', namespace='comment')),
    url(r'^(?P<lab_pk>[\d\w]+)/tags/', include('tags.urls', namespace='tags')),
    url(r'^(?P<lab_pk>[\d\w]+)/measurements/', include('measurements.urls', namespace='measurements')),
    url(r'^(?P<lab_pk>[\d\w]+)/search/', include('search.urls', namespace='search')),
    url(r'^profiles/', include('profiles.urls', namespace='profiles')),
    url(r"^(?P<lab_pk>[\d\w]+)/filemanager/", include("filemanager.urls")),
    url(r'^ckeditor/', include('ckeditor.urls')),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^admin/rosetta/', include('rosetta.urls')),
    url(r'^admin/', include(site.urls)),
    url(r'^jsi18n/$', 'django.views.i18n.javascript_catalog', js_info_dict, name='js_catalog'),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/labs/urls.py
from django.conf.urls import patterns, url
from labs.views import LabCreateView, LabListView, LabUpdateView, LabDetailView, LabDeleteView, BaseLabCreateView


urlpatterns = patterns('',
    url(r'^create/lab/$', LabCreateView.as_view(), name='create'),
    url(r'^(?P<lab_pk>[\d\w]+)/detail/lab/$', LabDetailView.as_view(), name='detail'),
    url(r'^(?P<lab_pk>[\d\w]+)/update/lab/$', LabUpdateView.as_view(), name='update'),
    url(r'^(?P<lab_pk>[\d\w]+)/delete/lab/$', LabDeleteView.as_view(), name='delete'),
    url(r'^create/test/lab/$', BaseLabCreateView.as_view(), name='create_test_lab'),
    url(r'^$', LabListView.as_view(), name='list'),
)

apps/comments/models.py
from documents import *

apps/comments/forms.py
# -*- coding: utf-8 -*-

from django import forms

from comments.documents import Comment
from common.forms import BaseForm
from common.widgets import CKEditorUploadWidget


class CommentForm(BaseForm):

    def __init__(self, *args, **kwargs):
        lab_pk = kwargs.pop('lab_pk')
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['text'].label = ''
        self.fields['text'].widget = CKEditorUploadWidget(config_name='ckeditor', lab_pk=lab_pk)
        self.fields['text'].widget.attrs['id'] = 'comment-create-{}-{}-{}'.format(self.prefix,
                                                                                  self.initial.get('instance_type'),
                                                                                  self.initial.get('object_id')
                                                                                  ).lower()

    object_id = forms.CharField(max_length=255, widget=forms.HiddenInput())

    class Meta:
        document = Comment
        fields = ('text', 'instance_type')
        widgets = {
            'instance_type': forms.HiddenInput(),
        }

apps/comments/views.py
# -*- coding: utf-8 -*-

from django.core.exceptions import PermissionDenied
from django.template import RequestContext
from django.template.loader import render_to_string
from django.views.generic import CreateView, UpdateView, DeleteView

from comments.forms import CommentForm
from common.mixins import LoginRequiredMixin, AjaxableResponseMixin, RecentActivityMixin, CheckLabPermissionMixin, \
    InitialLabMixin
from dashboard.documents import RecentActivity
from .documents import Comment
from labs.documents import Lab


class CommentCreateView(CheckLabPermissionMixin, AjaxableResponseMixin, InitialLabMixin, RecentActivityMixin, CreateView):
    """
    View for create comment
    """
    model = Comment
    form_class = CommentForm
    template_name = 'comments/comment.html'
    prefix = 'create'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.init_user = self.request.user
        self.object.object_id = form.cleaned_data['object_id']
        self.object.save()
        resent_activity = self.save_recent_activity(RecentActivity.COMMENT,
                                                    **{'comment_model': self.object.instance_type,
                                                    self.object.instance_type.lower(): self.object.object_id})
        return self.render_to_json_response({'data': render_to_string(self.template_name, {'comment': self.object},
                                                                      context_instance=RequestContext(self.request)),
                                             'resent_activity': render_to_string('dashboard/resent.html',
                                                                                 {'object': resent_activity})})


class CommentUpdateView(CheckLabPermissionMixin, InitialLabMixin, AjaxableResponseMixin, UpdateView):
    """
    View for editing an existing comment
    """
    model = Comment
    form_class = CommentForm
    template_name = 'comments/comment.html'
    prefix = 'update'

    def get_object(self, queryset=None):
        obj = super(CommentUpdateView, self).get_object(queryset)
        user = self.request.user
        lab = Lab.objects.get(pk=self.kwargs['lab_pk'])
        if user in lab.investigator or obj.init_user == user:
            return obj
        raise PermissionDenied

    def form_valid(self, form):
        self.object = form.save(commit=False)
        if not self.object.init_user:
            self.object.init_user = self.request.user
        self.object.object_id = form.cleaned_data['object_id']
        self.object.save()
        return self.render_to_json_response(
            {'data': render_to_string(self.template_name,
                                      {'comment': self.object, 'lab': Lab.objects.get(pk=self.kwargs['lab_pk'])},
             context_instance=RequestContext(self.request)),
             'pk': unicode(self.object.pk)}
        )


class CommentDeleteView(LoginRequiredMixin, AjaxableResponseMixin, RecentActivityMixin, DeleteView):
    """
    View for removing an existing comment
    """
    model = Comment

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        self.save_recent_activity(RecentActivity.DELETE, comment_model=self.object.instance_type)
        return self.render_to_json_response({'pk': unicode(self.object.pk)})

    def get_object(self, queryset=None):
        obj = super(CommentDeleteView, self).get_object(queryset)
        user = self.request.user
        lab = Lab.objects.get(pk=self.kwargs['lab_pk'])
        if user in lab.investigator or obj.init_user == user:
            return obj
        raise PermissionDenied

templates/comments/comment.html
{% load i18n %}
<div class="col-xs-12 comment-block" data-pk="{{ comment.pk }}">
  <div class="list-group-item list-group-item-info list-group-item-sm disabled">
    <strong>{{ comment.init_user.full_name }}</strong>

    <div class="pull-right">
      {{ comment.action_time|timesince }}
      {% if user == comment.init_user or user in lab.investigator %}
        <!--  <span class="input-group-btn"> -->
        <button class="btn btn-default btn-flat btn-xs comment-edit" type="button" data-toggle="modal"
                data-target="#comment-modal" data-url="{% url 'comment:update' lab_pk=lab.pk pk=comment.pk %}">
          <i class="fa fa-edit" title='{% trans "Edit" %}'></i>
        </button>
        <button class="btn btn-default btn-flat btn-xs" type="button" data-target="#confirm-delete-comment"
                data-toggle="modal"
                data-href="{% url 'comment:delete' lab_pk=lab.pk pk=comment.pk %}">
          <i class="fa fa-trash-o" title='{% trans "Remove" %}'></i></button>
        <!-- </span> -->
      {% endif %}
    </div>
  </div>
  <div class="list-group-item list-group-item-sm disabled">
    <div class="comment-context">{{ comment|safe }}</div>
  </div>
</div>

templates/comments/comment_form.html
{% load i18n bootstrap_tags %}

<div class="row">
  <div class="col-xs-12">
    <!-- Success box -->
    <div class="box box-solid box-info collapsed-box comments-block">
      {% if not not_collapse %}
      <div class="box-header">
        <h3 class="box-title"><i class="fa fa-comments-o"></i> {% trans 'Comments' %}</h3>

        <div class="box-tools pull-right">
          <button class="btn btn-info btn-sm pull-right" data-widget="collapse" title=""><i class="fa fa-plus"></i>
          </button>
        </div>
      </div>
      {% endif %}
      {% if not not_collapse %}
        <div class="box-body collapse">
      {% else %}
        <div class="box-body">
      {% endif %}
        <div id="comment" class="list-group comment-activities">
          {% for comment in comments %}
            {% include 'comments/comment.html' %}
          {% endfor %}
          {% include 'alert.html' with modal_id="confirm-delete-comment" class="comment-remove" %}
        </div>
        <!-- Primary box -->
        <div class="box box-solid box-default">
          <div class="box-header">
            <h3 class="box-title"><i class="fa fa-comment-o"></i> {% trans 'Add comment' %}</h3>

            <div class="box-tools pull-right">
              <button class="btn btn-info btn-sm" data-widget="collapse"><i class="fa fa-minus"></i></button>
            </div>
          </div>
          <form action="{% url 'comment:comment' lab_pk=lab.pk %}" method="post" id="comment-form" class="comment-form">
            <div class="box-body">
              {% csrf_token %}
              {{ comment_form_create|as_bootstrap }}
              {{ comment_form_create.media }}
            </div>
            <div class="box-footer text-right">
              <button type="submit" class="btn btn-info btn-sm btn-flat">{% trans 'Submit comment'|upper %}</button>
            </div>
          </form>
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->
    </div>
  </div>
</div>

<!-- /.col-md -->
{% if not not_modal %}
{% block modal %}
  {% include 'modal.html' with modal_id="comment-modal" action="" extra_form=comment_form_update modal_title='update  comment' %}
{% endblock %}
{% endif %}